### ISSUE TITLE
issues with generated pyproject.toml third party list

### ISSUE THREAD

**Issue by lewisacidic** [asottile/seed-isort-config#31]
Hi guys!

The generated pyproject.toml doesn't work for me with v4.3.16 of `isort`.  I think this is because the known_third_party entry in pyproject.toml is expected to be a comma-delimited string, rather than a list.

i.e.

```toml
[tool.isort]
known_third_party = "numpy,setuptools"
```

works

```toml
[tool.isort]
known_third_party = ["numpy", "setuptools"]
```

Doesn't.  seed-isort-config creates the latter.
