### ISSUE TITLE
Option to not remove libraries already in `known_third_party`

### ISSUE THREAD

**Issue by verhovsky** [asottile/seed-isort-config#48]
I'm using `pre-commit` with a repo that has a bunch of git submodules. I have a `.pre-commit-config.yml` in the top level repo, and I do `ln -s ../.pre-commit-config.yml .pre-commit-config.yml` from every submodule. If I configure seed-isort-config like this

```yml
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.4
    hooks:
    -   id: seed-isort-config
        args: [--settings-path=/path/to/my/root/repo]
```

then running `pre-commit run --all-files` from each submodule will overwrite `known_third_party` in the top level `isort.cfg` with values for the repo I'm running it from.

If I do with isort.cfg the same thing I do with .pre-commit-config.yml (as in the actual file in /path/to/my/root/repo/.isort.cfg and then symlinking `/path/to/my/roo/repo/sumbodule1/.isort.cfg` to that file), the same thing happens, known_third_party is overwritten to only work for the last submodule I ran it from. Running `pre-commit` from sumbodule1/ will overwrite `known_third_party` with just the libraries that are used in the submodule.

I could add an isort.cfg file to every single submodule, but because I'm using black, I need to put 5 lines of black-compatible boilerplate config in each file, while it shouldn't change, it still doesn't seem good.
