### ISSUE TITLE
QST: multiple application-directories

### ISSUE THREAD

**Issue by MarcoGorelli** [asottile/seed-isort-config#68]
Hi Anthony,

I'm trying to use this tool to populate `.isort.cfg` for a repository in which I have multiple projects. I've made a small repo which reproduces the issue [here](https://github.com/MarcoGorelli/seed-isort-mcve).

The structure of the repo is as follows:
```bash
$ tree -I '.git|__pycache__' -a
.
├── .gitignore
├── .isort.cfg
├── .pre-commit-config.yaml
├── application_1
│   ├── __main__.py
│   └── utils.py
└── my_subfolder
    └── application_2
        ├── __main__.py
        └── utils.py

3 directories, 7 files
```

Inside `application_1/utils.py`, I import `pandas`. Inside `my_subfolder/application_2/utils.py`, I import `numpy`.

Here is my `.pre-commit-config.yaml` file:
```yaml
repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config
        args: ['--application-directories=my_subfolder,.']
-   repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
    -   id: isort
```

If I run `pre-commit run --all`, then `.isort.cfg` is modified as follows:
```cfg
[settings]
known_third_party =application_1,pandas
```

I was expecting to see
```cfg
[settings]
known_third_party =numpy,pandas
```

Have I misunderstood how to use `seed-isort-config`, or am I using it wrong?
